<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Clearance Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 5px;
            font-size: 11px;
        }
        .header {
            text-align: center;
            margin-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            font-size: 14px;
        }
        .header h2 {
            margin: 5px 0;
            font-size: 13px;
        }
        .header h3 {
            margin: 5px 0;
            font-size: 12px;
        }
        .header p {
            margin: 1px 0;
            font-size: 10px;
        }
        .details, .requirements {
            margin-bottom: 10px;
        }
        .details h2 {
            font-size: 12px;
            margin: 5px 0;
        }
        .details p {
            margin: 2px 0;
        }
        .requirements ul {
            list-style-type: none;
            padding: 0;
        }
        .requirements li {
            margin-bottom: 3px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        th, td {
            border: 1px solid black;
            padding: 4px;
            text-align: left;
            white-space: pre-wrap;
            font-size: 10px;
        }
        th {
            background-color: #f2f2f2;
        }
        .footer {
            margin-top: 10px;
            text-align: right;
            font-size: 9px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Republic of the Philippines</h1>
        <h2>OCCIDENTAL MINDORO STATE COLLEGE</h2>
        <p>Labangan, San Jose, Occidental Mindoro</p>
        <p>Website: www.omsc.edu.ph | Email: omsc_9747@yahoo.com</p>
        <p>Tele/Fax: (043) 457-0225</p>
        <hr>
        <h3>Institutional Quality Assurance Office</h3>
    </div>
    <div class="details">
        <h2>{{ $clearance->document_name }}</h2>
        <p>Name of the Faculty: {{ $clearance->faculty_name ?? '____________________________' }}</p>
        <p>College/Department: {{ $clearance->department ?? '____________________________' }}</p>
        <p>Date Submitted: {{ $clearance->date_submitted ?? '____________________________' }}</p>
        <p>Checked by: {{ $clearance->checked_by ?? '____________________________' }}</p>
        <p>(For Professional Practitioners, e.g. lawyers, doctors, etc.)</p>
        <p>Note: All documents should be printed/photocopied in LONG COUPON BOND.</p>
    </div>
    <table>
        <thead>
            <tr>
                <th>List of Documents</th>
                <th>Complied</th>
                <th>Not Complied</th>
                <th>Not Applicable</th> 
            </tr>
        </thead>
        <tbody>
            @foreach($clearance->requirements as $requirement)
            <tr>
                <td>{{ $requirement->requirement }}</td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            @endforeach
        </tbody>
    </table>
    <div class="footer">
        {{-- <span>Generated by: {{ Auth::user()->name }}</span>  --}}
        {{-- <span>as of {{ now()->format('Y-m-d H:i:s') }}</span> --}}
        <span><strong>As of: </strong> {{ now()->format('F j, Y - H:i:s') }}</span>
        <span>|<strong> by:</strong> {{ Auth::user()->name }}</span>
    </div>
</body>
</html>